Update SonarCloudSecurity.yml

diff --git a/.github/workflows/SonarCloudSecurity.yml b/.github/workflows/SonarCloudSecurity.yml
--- a/.github/workflows/SonarCloudSecurity.yml
+++ b/.github/workflows/SonarCloudSecurity.yml
@@ -71,4 +71,10 @@ jobs:
         run: |
           $coverageFilePath = $env:COVERAGE_FILE_PATH
 
-          .\.sonar\scanner\dotnet-sonarscanner begin /k:"lind-exe_Statify" /o:"lind-exe" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.dotcover.reportsPaths="$coverageFilePath"
+          # Check if COVERAGE_FILE_PATH is set and valid
+          if (-not [string]::IsNullOrWhiteSpace($coverageFilePath)) {
+            .\.sonar\scanner\dotnet-sonarscanner begin /k:"lind-exe_Statify" /o:"lind-exe" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.dotcover.reportsPaths="$coverageFilePath"
+          } else {
+            echo "COVERAGE_FILE_PATH is not set or the coverage report path is invalid."
+            exit 1
+          }
